---
title: "Title here"
output: pdf_document
---

```{r setup, include=FALSE}
# Set chunk options here 

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rjags)
library(coda)
library(bayesmeta)
```

# Exercise 7

## Setup

```{r}
set.seed(44566)
mu <- 160
sigma <- 20
M <- 1000
X <- rnorm(M, mu, sigma)
```

## 1.

```{r}
glue::glue("True Values")
glue::glue("----")
glue::glue("mean: {mu}")
glue::glue("standard deviation: {sigma}")
glue::glue("variance: {sigma^2}")
glue::glue("median: {mu}")
glue::glue("0.025, 0.5 and 0.975 quantiles:")
qnorm(c(0.025, 0.5, 0.975), mu, sigma)
```

## 2.

```{r}
coda::traceplot(mcmc(X))
```

## 3.

```{r}
tibble(x = X) |> ggplot(aes(x = x)) + 
  geom_histogram(aes(y=after_stat(density)), bins = 30) + 
  stat_function(fun = dnorm, args = list(mu, sigma), color="blue", linewidth = 2) +
  labs(title = "Histogram of X", x = "X", y = "Frequency")
```

## 4.

```{r}
glue::glue("Estimated Values")
glue::glue("------")
glue::glue("mean: {mean(X)}")
glue::glue("standard deviation: {sd(X)}")
glue::glue("variance: {var(X)}")
glue::glue("median: {median(X)}")
glue::glue("0.025, 0.5 and 0.975 quantiles:")
{quantile(X, probs = c(0.025, 0.5, 0.975))}
```

## 5.

```{r}
glue::glue("Estimated P[X > 175]: {mean(X > 175)}")
glue::glue("True P[X > 175]: {pnorm(175, mu, sigma, lower.tail = FALSE)}")
glue::glue("")
glue::glue("Estimated P[150 < X < 180]: {mean(X > 150 & X < 180)}")
glue::glue("True P[150 < X < 180]: {pnorm(180, mu, sigma) - pnorm(150, mu, sigma)}")
```
