\documentclass[english]{beamer}

%% The most common packages are already included in:
\usetheme{biostat}
\usepackage{xcolor}
\usepackage{hyperref}

%% Custom color for links (biostat blue)
\definecolor{mylinkcolor}{RGB}{0,40,165}

\hypersetup{
  colorlinks=true,
  urlcolor = mylinkcolor,
  linkcolor=mylinkcolor,
  urlcolor=mylinkcolor,
  citecolor=mylinkcolor,
  filecolor = mylinkcolor
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Header data: (adjust to your needs:
\def\uzhunit{STA421 Foundations of Bayesian Methodology}             %% if (not) needed comment/uncomment
%\def\uzhunitext{STA480}

\title[Monte Carlo method]{History of the Monte Carlo method}
%% Optional Argument in [Brackets]: Short Title for Footline

%% The following are all optional, simply comment them
\subtitle{\textbf{Big picture contribution}}
%%\institute{STA480 Statistical consulting}  %% optional
\author{Group 2: Jan Hohenheim, Holly Vuarnoz, Sophie Haldemann,
Andrea Staub, Emanuel Mauch}
\date{\today}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<include=FALSE,purl=FALSE>>=
library(knitr)
opts_chunk$set(
fig.path='figures/fig', fig.show='hold',
	cache=TRUE, fig.height=4.5)
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
\maketitle


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Introduction
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}{The History}

\begin{itemize}\setlength\itemsep{1em} % Increase spacing here
    \item Revolutionary idea of Comte de Buffon (1707-1788):
    \begin{itemize}
      \item Using randomness in a deterministic way
      \item Buffon's Needle for calculating Pi (\(\pi\)) 
    \end{itemize}
    \item 1940s Los Alamos, World War II:
    \begin{itemize}
      \item Simulations for nuclear weapons research
      \item Named after Monte Carlo Casino in Monaco
    \end{itemize}
\end{itemize}

\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% The Method
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}{The Method}

Many simulations follow this pattern:
\begin{itemize}
  \item Model system with probability density functions (PDFs)
  \item Sample repeatedly from PDFs
  \item Compute statistics of interest
\end{itemize}

Requirement: \textbf{exact object is known}\\
$\rightarrow$ e.g. finance, physics and engineering
\end{frame}



\begin{frame}{Marble Example: Estimating Pi (\(\pi\))}

\begin{figure}
  \includegraphics[width=0.45\textwidth]{marble}
  \hspace{0.5cm} % Spacing between the images
  \includegraphics[width=0.45\textwidth]{marble2}
  \caption{The number Pi is determined by randomly dropping marbles into two bowls. Proportion of marbles ending up in the two bowls approaches \(\pi\) as the simulation progresses. See \href{https://www.youtube.com/watch?v=7ESK5SaP-bc}{YouTube video}.}
\end{figure}
\end{frame}

\begin{frame}{Law of Large Numbers}
Let \((X_1, \ldots, X_n)\) be a sequence of independent and identically distributed (i.i.d.) random variables with finite expectation \(\mu\). Then, as \(n \rightarrow \infty\),

\[
\frac{1}{n} \sum_{i=1}^{n} X_i \overset{P}{\rightarrow} \mu
\]

\cite{held2014}.


\end{frame}



\begin{frame}{Inverse Transform Sampling: Generating Samples}

\begin{itemize}
  \item Generate i.i.d. samples from uniform distribution [0, 1]
  \item Inverse transform sampling:
    \begin{itemize}
        \item Apply inverse CDF to transform uniform samples to target distribution
        \item Works because \(P[F^{-1}(U) \leq x] = P[U \leq F(x)] = F(x)\)
    \end{itemize}
  \item Example: Exponential distribution
    \begin{itemize}
        \item For \(F(x) = 1 - \exp(-\lambda x), x \geq 0\),
        \item Set \(1 - \exp(-\lambda x) = u\),
        \item Solve for \(x\): \(x = -\frac{1}{\lambda} \log(1 - u)\)
    \end{itemize}
  \item Enables sampling from any distribution with known inverse CDF
\end{itemize}

\end{frame}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Example from Worksheet 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


<<part2, echo=FALSE, fig.height=4.5, fig.width=6>>=
library(coda)
library(ggplot2)
library(tidyverse)
@

\begin{frame}[fragile]{Worksheet 1: Random Sample vs True Distribution}
Let the random variable \(X \sim N(\mu, \sigma^2)\), with \(\mu = 160\) and \(\sigma = 20\). Generate a Monte Carlo sample \(Xs\) of size \(M = 1000\).

\begin{knitrout}\small
<<setup, echo=TRUE>>=
M <- 1000
mu <- 160
sigma <- 20
set.seed(44566)
Xs <- rnorm(n = M, mean = mu, sd = sigma)
@
\end{knitrout}
\end{frame}




\begin{frame}[fragile]
<<part3, echo=FALSE, fig.align='center'>>=
par(mfrow = c(1, 2), cex = 0.9, pty = "s")
plot(seq_along(Xs), Xs,
     type = "l",
     xlab = "Sample",
     ylab = "Xs",
     main = "Traceplot", cex = 0.5)
hist(Xs, freq = FALSE,
     ylim = c(0, 0.02), breaks = 20)
curve(dnorm(x, mean = mu, sd = sigma),
      from = min(Xs), to = max(Xs),
      add = TRUE, col = "red", lwd = 2)
legend("topleft", c("simulated", "true density"), pch = c(22, NA), lwd = c(NA, 2),
       bty = "n", col = c("black", "red"), cex = 0.8)
@
\end{frame}


\begin{frame}{Take Home Message}
\textbf{Why we use it}: 
\begin{itemize}
\item In Bayesian analysis posteriors aren't easy to work with
\item Calculation of integrals is complex
\item Monte Carlo simulation is used to numerically solve a complex problem through repeated random sampling
\end{itemize}
\end{frame}




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}{Bibliography}
   \footnotesize
   \bibliographystyle{apalike}
   \nocite{held2014}
   \nocite{Harrison2010}
   \nocite{Marble2020}
\bibliography{biblio}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
